### PR TITLE
Update XMLStream.php

### PR DESCRIPTION
**Pull request by ViPErCZ**
Fix Fatal error: Function name must be a string + typos

### CODE REVIEW

**Comment by fahad19** [comment]
hey @ViPErCZ, thanks for the PR! I don't maintain this fork any more. would you like me to add you here as a contributor?

**Comment by ViPErCZ** [comment]
I was now in charge of one project that uses this repository. OK thanks.

**Comment by fahad19** [comment]
@ViPErCZ: Hi Martin, I just added you to the repo. Welcome!

**Comment by ViPErCZ** [comment]
Thanks!

**Pull request merged**
